m

diff --git a/AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml b/AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml
--- a/AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml
+++ b/AwsCryptographicMaterialProviders/codebuild/release-python/prod-release.yml
@@ -16,6 +16,15 @@ phases:
       python: latest
   pre_build:
     commands:
+      # Assert we are not releasing "aws-cryptographic-material-providers==10.0.0" to prod PyPI.
+      # A bad release has already been uploaded under this name/version to prod PyPI.
+      # This release has been deleted.
+      # Prod PyPI does not allow re-uploading a release under a new name/version.
+      - |
+        if expr ${FOUND_VERSION} != ${VERSION}; then
+          echo "Cannot release 10.0.0"
+          exit 1;
+        fi
       # Get Dafny
       - export dafnyVersion=$(grep '^dafnyVersion=' project.properties | cut -d '=' -f 2)
       - cd ..
