m

diff --git a/AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml b/AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml
--- a/AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml
+++ b/AwsCryptographicMaterialProviders/codebuild/release-python/validate.yml
@@ -4,6 +4,11 @@ version: 0.2
 # by installing it from PyPI
 # then running tests from source against the published artifact.
 
+# For the MPL package, which has the ESDK as a downstream dependency,
+# also validate that the released artifact is usable by the ESDK
+# by downloading the ESDK from source
+# and running tests with the newly published MPL artifact.
+
 phases:
   install:
     commands:
@@ -29,6 +34,11 @@ phases:
       # The tests will use the installed package, not the local code.
       # The actual test code must be from local, since we don't publish tests.
       - pip install aws-cryptographic-materialproviders==$VERSION
+      # Install ESDK-Python, override its requirements to force use of the just-published MPL version
+      - git clone https://github.com/aws/aws-encryption-sdk-python.git
+      - cd aws-encryption-sdk-python
+      - sed -i "s/aws-cryptographic-materialproviders/aws-cryptographic-materialproviders==$VERSION/" requirements_mpl.txt
+      - cd ..
       # Get CI Creds to be able to call KMS
       - TMP_ROLE=$(aws sts assume-role --role-arn "arn:aws:iam::370957321024:role/GitHub-CI-MPL-Dafny-Role-us-west-2" --role-session-name "MPL-Python-Test-Release")
       - export TMP_ROLE
@@ -39,8 +49,41 @@ phases:
   build:
     commands:
       - NUM_RETRIES=3
+      # First, run tests with the published package
       - cd AwsCryptographicMaterialProviders
-      # Transpile code (for tests)
       - make transpile_python
       - cd runtimes/python
       - python -m pytest test/ -s -v
+      # Then, run ESDK local tests with the new MPL artifact installed
+      - cd ../../../aws-encryption-sdk-python
+      - |
+        while [ $NUM_RETRIES -gt 0 ]
+        do
+          tox -e py311-local-mpl
+          if [ $? -eq 0 ]; then
+            break
+          fi
+          NUM_RETRIES=$((NUM_RETRIES-1))
+          if [ $NUM_RETRIES -eq 0 ]; then
+            echo "All validation attempts failed, stopping"
+            exit 1;
+          else
+            echo "Validation failed, retrying in 60 seconds; will retry $NUM_RETRIES more times" && sleep 60
+          fi
+        done
+      # Then, MPL-only local tests with the MPL installed
+      - |
+        while [ $NUM_RETRIES -gt 0 ]
+        do
+          tox -e py311-mpllocal-mpl
+          if [ $? -eq 0 ]; then
+            break
+          fi
+          NUM_RETRIES=$((NUM_RETRIES-1))
+          if [ $NUM_RETRIES -eq 0 ]; then
+            echo "All validation attempts failed, stopping"
+            exit 1;
+          else
+            echo "Validation failed, retrying in 60 seconds; will retry $NUM_RETRIES more times" && sleep 60
+          fi
+        done
